version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=django-insecure-cxv+9)m7#8zvu$@d)7b+9)cr))p=3gzlh)_(srhe=(49+@r194
      - DEBUG=False
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - backend
    volumes:
      - ./core:/app
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - "80:80"
    depends_on:
      - redis
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
volumes:
  static_volume:
  media_volume: